### ISSUE TITLE
며칠 전부터 잘 작동이 안되네요

### ISSUE THREAD

**Issue by migig3** [Escaper-Park/unofficial_chzzk_android_tv#1]
방송 목록이 아예 안 뜨거나
떠도 방송에 진입이 안 되고 그러네요ㅠ
될 때도 있고 안 될 때도 있고 그래요
채팅이 안 뜰 때도 있고..
엔비디아 쉴드TV 2세대 쓰고 있습니다

**Comment by Escaper-Park** [comment]
안드로이드 앱 설정에서 캐시를 삭제하시고 다시 시도해보세요.
그래도 반복된다면 재설치 후 다시 실행해보세요.

**Comment by Escaper-Park** [comment]
설치파일 중 v8과 v7 모두 설치가 되시나요? 정상적이라면 둘 중 하나만 설치되어야 할텐데요. 
통합파일로 재설치도 해보셨나요?
그리고 혹시 해당 기기에서 다른 앱들은 정상작동 하나요?

**Comment by migig3** [comment]
7과8은 설치 잘 되고 x86은 설치 안 돼요
통합판으로 일단 써 볼게요
네 유튜브 트위치 아프리카 등 다른 앱은 잘 작동합니다
치지직도 그동안 잘 됐었는데 며칠 전부터 이러네요ㅜ

**Comment by Escaper-Park** [comment]
> 7과8은 설치 잘 되고 x86은 설치 안 돼요 통합판으로 일단 써 볼게요 네 유튜브 트위치 아프리카 등 다른 앱은 잘 작동합니다 치지직도 그동안 잘 됐었는데 며칠 전부터 이러네요ㅜ

로그인 쿠키 기간 만료 에러는 사실 네트워크 문제로 로그인이 정상적으로 진행되지 않았을 때도 해당 메시지가 뜹니다.
방송목록이 안나올 때 같이 나온다는건 네트워크쪽에 문제가 있어서 데이터를 정상적으로 받아오지 못한다는 걸 뜻합니다.

증상을 종합해보면 치지직에서 데이터를 제대로 받아오지 못하는 것 같은데, 치지직 자체 API는 변한 것이 없습니다. 
다른 앱들은 정상적으로 작동한다고 하시지만, @migig3 님의 네트워크쪽 문제일 가능성도 생각해 보시는 게 좋을 것 같습니다.

우선 원인 파악이 잘 안되니 해당 증상을 겪으신 다른 분들이 계시면 앱 쪽 문제를 다시 확인해보겠습니다.
증상이 개선되지 않으면, 불편하시겠지만 다음 업데이트까지 크롬캐스트를 통해서 시청하시는 것을 추천드립니다.

**Comment by migig3** [comment]
원인을 찾은 것 같습니다
제 거에 서프샤크vpn이 깔려 있었는데 이놈이 제멋대로 혼자 켜지고 있었네요
치지직은 해외에서 잘 접속이 안 된다고 하니 그래서 문제가 생겼던 거 같습니다
VPN 삭제하니 다시 빠르게 잘 되네요
제 문제가 맞았네요;;
앱 잘 쓰고 있습니다 감사합니다
