### ISSUE TITLE
어플은 켜지지만 방송이 안눌러짐

### ISSUE THREAD

**Issue by Gundarl** [Escaper-Park/unofficial_chzzk_android_tv#11]
빔프로젝터: hy320.
버전: 0.31 세 버전 모두 동일.
증상: 어플 메인화면 켜지고 로그인도 되지만 아무 방송에도 못들어감. 마우스 연결해서 클릭해도 마찬가지. 아무 반응 없음.

감사합니다.

**Comment by Escaper-Park** [comment]
#### 질문 사항
0. 설치 버전이 v0.3.1+3 버전인가요? 최근 핫픽스 업데이트를 했으니 확인해주세요.

1. 방송에 못 들어 간다는 건 아예 클릭이 안된다는 건가요? 아니면 들어간 후 라이브 로딩중... 과 같은 화면이나 어두운 화면이 보이고 재생이 안된다는 건가요?

2. 방송 실행(클릭) 후 앱이 멈추나요? 아니면 다른 동작은 가능하나요?

3. 기존 버전을 사용하셨었나요? 그렇다면 기존 버전은 제대로 작동하나요? (v0.2.6+1 버전 등)

4. 설치 시 기존 버전을 삭제하고 다시 설치하셨나요?

#### 조치 사항
1. 기계를 완전히 재부팅하고 다시 실행해보세요. (안드로이드 설정 - 기기 환경 설정 - 다시 시작)

2. 확인 버튼만 작동이 되지 않는다면 리모콘 앱을 설치해서 사용해보세요. Flutter Framework의 일부 버전과 일부 리모컨 간 호환성 문제가 있습니다. 기존 버전에서 문제가 없었더라도, 프레임워크 버전을 업데이트 했기 때문에 문제가 생길 수 있습니다.

**Comment by Gundarl** [comment]
v0.3.1+3 버전입니다.
v7과 v0.3.1+3.apk 는 설치는 되지만 라이브 방송 실행이 안되고 v8a.apk는 아예 설치가 안됩니다. 
재설치-리부트 해도 마찬가지 입니다. 

방송 실행(클릭) 후 앱이 멈추지는 않습니다. 
메인화면에 뜬 라이브 방송 아무거나 누르면 마우스로 클릭한 듯이 짧게 회색으로 제목이 바뀌지만 영상이 틀어지진 않습니다. 

리모컨 앱을 설치해보려고 하는데 프로젝터가 인식을 못하네요 ㅠㅠ 좀 더 찾아봐야겠습니다.

감사합니다.

**Comment by Escaper-Park** [comment]
https://github.com/Escaper-Park/unofficial_chzzk_android_tv/releases/tag/v0.2.6%2B1

v0.3.1 삭제하시고 위 링크의 구버전(v0.2.6+1)으로 설치 후 실행해보세요.
구버전도 작동하지 않는다면 기기 문제일 가능성이 높습니다.

구버전도 싱글뷰 시청은 큰 차이가 없으니 제대로 작동한다면 구버전 사용하시는걸 추천합니다.

**Comment by Gundarl** [comment]
구버전 (0.2.6+1) 설치하니까 잘 나옵니다. 
새버전은 왜 안되는지 모르겠네요 ㅠㅠ
아무튼 너무 감사합니다!

**Comment by Escaper-Park** [comment]
> 구버전 (0.2.6+1) 설치하니까 잘 나옵니다. 새버전은 왜 안되는지 모르겠네요 ㅠㅠ 아무튼 너무 감사합니다!

새 버전 업데이트 할 때 개발 프레임워크 Flutter 버전을 업데이트 했는데 호환 문제가 있을 수도 있고 여러 추측은 가능하지만 제가 해당 기기를 가지고 있지 않아서 직접적인 디버깅은 어렵네요. 혹시 새로운 버전 사용을 원하신다면 escaper.bgp@gmail.com으로 메일 주소 보내주세요. 프레임워크 버전 다운그레이드 해서 다시 build 한 다음 파일 보내드리도록 하겠습니다 (정상 작동은 장담 못합니다).
