### ISSUE TITLE
디시보기 화질

### ISSUE THREAD

**Issue by Damnuuu** [Escaper-Park/unofficial_chzzk_android_tv#12]
다시보기 vod
화질이 1080p로 고정되거나
변경가능 옵션이 있으면 좋을꺼 같아요
재생시 1080이 아니라 720으로 재생되서 보기가 살짝 아쉽네요
감사합니다

**Comment by Escaper-Park** [comment]
사용 중인 앱 버전이 어떻게 되시나요?

현재 다시보기 화질은 '자동'으로 설정되어 네트워크 상황에 맞는 최고화질로 설정됩니다. 네트워크 상황이 괜찮다면 수 초 내에 1080p로 설정 됩니다.

**Comment by Escaper-Park** [comment]
[v0.3.3](https://github.com/Escaper-Park/unofficial_chzzk_android_tv/releases/tag/v0.3.3) 에서 화질 설정 기능을 추가하였습니다.
