### ISSUE TITLE
방송, VOD 종료시 화면 꺼짐 기능, 예약종료 기능 요청드립니다.

### ISSUE THREAD

**Issue by xvasonix** [Escaper-Park/unofficial_chzzk_android_tv#13]
방송, VOD 종료시 화면 꺼짐 기능, 예약종료 기능 요청드립니다.
방송 종료시 화면 꺼짐 기능이 지금 있는 것 같기는 한데, 가끔씩 안꺼지고 그대로 켜진 경우도 있는 것 같습니다.
VOD는 꺼짐 기능이 없어 보이던데.. 매번 확인 할 수가 없어서 딱 이렇다 저렇다 말씀 드리기가 애매하네요...

혹시 예약 타이머 종료 기능... 추가가 가능할까요?

좋은 앱 만들어주셔서 감사합니다. 잘 쓰고 있습니다!

(정식앱은 다시보기에 이전 채팅도 같이 보이게 추가 됐더라구요, API가 제공되는지 모르겠군요.. 네이버가 해야할 일을 대신 하시느라 고생 많으십니다!)

**Comment by Escaper-Park** [comment]
1. 방송 종료 시 화면보호기 작동은 테스트 상황에서는 문제가 없었는데 실 상황에서 작동하지 않는 경우가 있나보네요. 확인해보겠습니다.
2. Vod는 이미 설정되어 있습니다.
3. 예약 타이머 기능은 추가할 생각이 없습니다. VOD 다시보기 채팅과 같은 필수 업데이트 빼고는 다른 기능을 추가할 생각이 없습니다. 버그 수정 정도만 업데이트할 예정입니다.
4. 처음부터 공식 API는 제공되는 것이 없고, 웹 브라우저에서 개발자 도구를 뜯어보고 적용합니다. 다행히 다시보기 채팅 기능은 서버측 암호화 같은 기술이 적용되지 않아 기능 추가가 가능할 것으로 보입니다. 조만간 업데이트 예정입니다.
