### ISSUE TITLE
apk 다운로드 aftvnews 를 이용하면 쉽게 할 수 있더군요. 

### ISSUE THREAD

**Issue by diyso** [Escaper-Park/unofficial_chzzk_android_tv#16]
사이트 : https://www.aftvnews.com/downloader/

테스트는 샤오미 tv 스틱을 이용해서 해보았습니다. 
링크를 단축 링크로 만들어 주고 번호를 부여해 줘서 번호를 입력을 하면 해당 링크를 다운로드 할 수 있는 방법으로
제공 되더군요. 

참고 : https://github.com/yuliskov/SmartTube

참고 한 사이트는 tv에서 유튜브를 광고 없이 사용할 수 있는 smarttube 의 다운로드 방식이 좋을 듯 해서 테스트 한 것이며
구글 app 스토어에서 Downloader 라는 이름의 app이 등록되어져 있습니다. 

현재 최신 빌드 번호가 부여하고 있어서 매번 수정을 해줘야 하는 불편함은 있지만. 그래도 직접 다운로드 설치를 할 수 있으니
조금 다른 방법 보다는 편하다라는 느낌이 들더군요.. 

만들어진 코드 

code : 552910
주소 : http://aftv.news/552910
연결 된 주소 : https://github.com/Escaper-Park/unofficial_chzzk_android_tv/releases/download/v0.3.3%2B1/chzzk-v0.3.3+1-v7a.apk

요렇게 구성되며.. 저 코드만 입력을 하면 연결 된 apk 주소를 다운로드 후 바로 설치 가 이루어집니다. 

뭐.. 그렇습니다. ㅎ.

**Comment by Escaper-Park** [comment]
해당 방법을 통해 설치했을 때 발생하는 어떠한 문제(보안 등)에 대해서도 저는 책임지지 않습니다. 사용자 분들께서 알아서 판단하시고 사용하시길 바랍니다.
