### ISSUE TITLE
로그인시 블루투스 키보드 입력 가능 여부

### ISSUE THREAD

**Issue by yanpaper** [Escaper-Park/unofficial_chzzk_android_tv#17]
현재 버전 : 0.32
사용 기기 : 크롬캐스트 with google tv

다른 어플에서 키보드 정상입력되는 것을 확인하였습니다
현재 어플에서도 방향키와 엔터는 정상적으로 적용 가능합니다

다만 로그인창과 검색창에서 방향키와 엔터 이외에 다른 글자키나 숫자키로 입력이 되지 않습니다

스크린 키보드 입력만 허용되는것으로 보이는데
오류인가요?
아니면 의도된것이라면, 향후에 개선이 가능할까요?

**Comment by Escaper-Park** [comment]
몇몇 TV에서 스크린 키보드가 제대로 작동하지 않는 현상과 Native 가상 키보드의 느린 반응속도 때문에 앱 자체 가상 키보드를 만들어 사용한 것입니다.

따라서 블루투스 키보드 입력은 안되는게 맞으며, 다시 사용되도록 변경할 생각이 없습니다. (사용이 안되도록 한 것이 개선책이기 때문에)
