### ISSUE TITLE
멀티뷰 사용시 2개가 죽습니다.

### ISSUE THREAD

**Issue by Ralfj1917171** [Escaper-Park/unofficial_chzzk_android_tv#18]
1,2 까지는 재생되는데
뭔짓을 해도 3과 4는 방종이라고 뜨고 실행이 안됩니다.
버전 다운해서 쓰고 있는데 거긴 또 4개 멀티뷰가 됩니다.

기존 0.2.6인가 사용했고 지금은 최신버전 유니버셜입니다.

**Comment by Escaper-Park** [comment]
Universal 버전은 설치에 문제가 있는 분들을 위한 v7a, v8a, x86 통합 버전입니다. 따라서 여러 문제가 있을 수 있다고 Release(download) 페이지의 설치가이드에 설명을 해놓았습니다.
[v0.3.3+1](https://github.com/Escaper-Park/unofficial_chzzk_android_tv/releases/tag/v0.3.3%2B1)

v7a, v8a가 최적화 버전이니 사용하시는 TV의 AP가 64bit를 지원하면 v8a 아니면 v7a로 설치해서 사용해보세요.

대부분 TV에서 v7a로 사용 가능합니다. 그리고 설치 시 기존 버전을 삭제하고 설치해주세요.
