### ISSUE TITLE
리모컨 조작 없을 시 화면보호기

### ISSUE THREAD

**Issue by chartw** [Escaper-Park/unofficial_chzzk_android_tv#2]
이스트라 쿠카 2023 사용중입니다.
초기버전에서는 이러지 않았는데, 버전업 이후 리모컨 조작 없을시 화면보호기가 켜집니다.

**Comment by Escaper-Park** [comment]
> 이스트라 쿠카 2023 사용중입니다. 초기버전에서는 이러지 않았는데, 버전업 이후 리모컨 조작 없을시 화면보호기가 켜집니다.

화면 꺼짐 방지를 위해 Wakelock 패키지를 적용했는데 작동하지 않는 경우가 있는 것 같습니다.

불편하시겠지만 다음 업데이트까지 안드로이드 시스템 화면보호기 설정을 바꿔서 사용해주세요. 감사합니다.

**Comment by chartw** [comment]
@Escaper-Park
설치 파일 바꾸니 화면보호기 안켜지네요
바꾸기 전 chzzk-release.v0.1.1.apk
바꾼 후 chzzkTV-armeabi-v7a-release-v0.1.1.apk

**Comment by Escaper-Park** [comment]
> @Escaper-Park
> 
> 설치 파일 바꾸니 화면보호기 안켜지네요
> 
> 바꾸기 전 chzzk-release.v0.1.1.apk
> 
> 바꾼 후 chzzkTV-armeabi-v7a-release-v0.1.1.apk

피드백 감사드립니다. 다음 업데이트 릴리즈 때는 통합설치파일 제외하고 업로드 해야겠네요 :)
