### ISSUE TITLE
리모콘의 확인버튼

### ISSUE THREAD

**Issue by Damnuuu** [Escaper-Park/unofficial_chzzk_android_tv#3]
utv uhd3
uie4027lgu
안드tv os 빌드 12
안드로이드 셋탑박스에 설치해서 사용중입니다.
리모콘의 확인버튼이 작동하지않아요.

방송시청중 위로 버튼을 눌러서 나오는 방송목록에서 리모콘의 확인버튼이나 마우스의 왼클릭으로도 작동하지 않습니다.

**Comment by Damnuuu** [comment]
채널의 전체 목록을 볼 수 없습니다.
설정을 클릭 할 수 없습니다.

**Comment by Escaper-Park** [comment]
> utv uhd3 uie4027lgu 안드tv os 빌드 12 안드로이드 셋탑박스에 설치해서 사용중입니다. 리모콘의 확인버튼이 작동하지않아요.
> 
> 방송시청중 위로 버튼을 눌러서 나오는 방송목록에서 리모콘의 확인버튼이나 마우스의 왼클릭으로도 작동하지 않습니다.

현재 유플러스 셋탑박스, 리모컨과 앱 간의 호환성 문제가 있습니다. 

테스트 기기가 없어서 디버깅이 불가능하여 당장 해결하기는 어렵고, 

유플러스에서 제공하는 모바일 리모컨 앱을 사용하셔야 합니다.

[유플러스 리모컨 앱 정보](https://www.lguplus.com/iptv/main-feature/000PPT0036)

**Comment by Damnuuu** [comment]
알겠습니다
댓글의 문제도 같은 맥락인가요?

**Comment by Escaper-Park** [comment]
> 알겠습니다 댓글의 문제도 같은 맥락인가요?

리모컨 앱 사용하시면 정상적으로 사용하실 수 있을겁니다.
