### ISSUE TITLE
19세 설정된 다시보기는 볼 수가 없네요

### ISSUE THREAD

**Issue by migig3** [Escaper-Park/unofficial_chzzk_android_tv#4]
19세 설정된 다시보기는 로그인 해야 볼 수 있다고 뜹니다. 
로그아웃하고 다시 로그인하고 들어가 봐도 똑같이 뜹니다.
19세 설정된 생방송은 잘 들어가지는데 다시보기는 안 되네요

**Comment by Escaper-Park** [comment]
해당 버그는 이미 수정하였는데 (dev branch) 다른 일 때문에 업데이트가 좀 늦어지고 있습니다. 
오늘이나 내일 새로운 버전 업데이트 예정입니다.

업데이트 전 까지
팔로우 한 채널의 경우 팔로우 -> 채널 선택 -> 동영상 옆의 '>' 표시를 눌러 동영상 전체보기 페이지에 들어가셔서 시청 부탁드립니다.

카테고리에서 동영상도 마찬가지로 해당 채널 검색하셔서 들어가신 후 위와 같이 시청 부탁드립니다.

**Comment by migig3** [comment]
말씀대로 하니 되네요 감사합니다
