### ISSUE TITLE
다시보기 시간

### ISSUE THREAD

**Issue by mizzzzzzzzzzz** [Escaper-Park/unofficial_chzzk_android_tv#5]
VOD 다시보기 시청시간이 유지될수있으면 좋겠습니다

**Comment by Escaper-Park** [comment]
> VOD 다시보기 시청시간이 유지될수있으면 좋겠습니다

해당 기능의 경우 개발을 고려한 적이 있긴 한데 생각보다 작업해야 할 게 많은 기능이라 귀찮아서 안 하고 있었습니다.

치지직 정출 이후에 네이버에서 TV 앱 개발 관련 로드맵이나, 앱 개발 의지가 보이지 않으면 그때 업데이트를 고려해 보겠습니다.
