### ISSUE TITLE
성인 인증 채널 채팅 못 불러오는 증상

### ISSUE THREAD

**Issue by pastelsky911** [Escaper-Park/unofficial_chzzk_android_tv#7]
처음에는 괜찮았는데 최근 1~2주 전부터 

성인 인증 채널들에서 채팅을 불러오지 못하는 이슈가 있습니다

이번 0.2.5 버전도 동일하게 못 불러오는데 해당 부분 확인이 가능할까요?

항상 감사합니다

**Comment by Escaper-Park** [comment]
제보 감사드립니다. 해당 현상 수정하였습니다. 

기존 앱은 삭제 안하고 덮어쓰기로 설치하셔도 될겁니다.

[v0.2.5+1](https://github.com/Escaper-Park/unofficial_chzzk_android_tv/releases/tag/v0.2.5)
