### ISSUE TITLE
채팅 입력 기능

### ISSUE THREAD

**Issue by migig3** [Escaper-Park/unofficial_chzzk_android_tv#8]
라이브 방송에서 채팅 입력 기능.. 혹시 추가될 수 있을까요?

앱은 너무 잘 쓰고 있습니다

**Comment by Escaper-Park** [comment]
가능은 합니다만 개인적으로 리모콘을 이용해 타자를 치는것은 엄청나게 비효율적이라고 생각되고, 티비 채팅 사용자도 많지 않을것이라고 예상되기 때문에 추가할 생각은 전혀 없습니다.

채팅은 모바일을 이용해주세요.

**Comment by migig3** [comment]
블루투스 키보드를 연결해서 치면.. 알겠습니다ㅜ
