### ISSUE TITLE
앱내 카테고리 즐겨찾기 에러

### ISSUE THREAD

**Issue by rafrentia** [Escaper-Park/unofficial_chzzk_android_tv#9]
앱내 카테고리 즐겨찾기 기능이 며칠전부터 에러가 납니다. 확인부탁드립니다

잘사용하고 있으며 너무 감사드립니다.

**Comment by Escaper-Park** [comment]
어떤 상황에서 에러가 나타나나요? 
1. 홈 화면 즐겨찾기에 에러 메시지가 나타남.
2. 즐겨찾기 추가가 되지 않음.
3. 특정 카테고리를 추가했더니 즐겨찾기에 나타나지 않거나 에러가 나타남.

**Comment by rafrentia** [comment]
1. 카테고리에서 즐겨찾기 추가 버튼이 모두 즐겨찾기 에러 버튼으로 교체돼있음.
2. 기존 추가해놓았던 즐겨찾기들도 즐겨찾기에서 나타나지 않음.
![20240806_200215](https://github.com/user-attachments/assets/1dedfdaa-d480-4338-b10c-9f5c2d9143b4)

**Comment by Escaper-Park** [comment]
아마도 로컬 데이터에 문제가 있나 보네요. 

안드로이드 설정 - 앱 - 치지직 - 데이터 삭제 후 다시 실행해 주시거나 앱을 삭제 후 재설치 해주세요.

* 현재 버전까지 카테고리 즐겨찾기가 로컬에 저장 중이라서 기존 저장된 즐겨찾기는 삭제될 겁니다.
다음 버전에 치지직 카테고리 팔로잉과 연동 예정입니다.

**Comment by rafrentia** [comment]
말씀주신게 맞네요. 앱업데이트 해봤었는데.. 데이터 삭제 없이 업데이트 해서 해결이 안됐었나봅니다.

감사합니다
